### ISSUE TITLE
看了table里的记录

### ISSUE THREAD

**Issue by ichirika** [hoosin/EveryDaySport#10]
有种莫名的感慨。
一是坚持好难。二是时间过的好快。
当2015年的table中的记录，还停留在1月。
而现在却已是2016年1月的第二天的末尾。。

就这一刻。我感觉光阴似箭、日月如梭。
新年愿望，希望坚持锻炼，达成Planche。

**Comment by hoosin** [comment]
对，很难坚持的 @YuSuu @smallke

**Comment by szdsy** [comment]
加油！

**Comment by UncleSusan** [comment]
加油。

**Comment by YuSuu** [comment]
但愿能一天比一天好 xD @hoosin

**Comment by YuSuu** [comment]
谢谢鼓励 @szdsy @UncleSusan

**Comment by smallke** [comment]
加油 @hoosin

**Comment by ouding517** [comment]
你要加油啊

**Comment by haosss** [comment]
很有意思额~
加油、

**Comment by 836104726** [comment]
原来不是那个知乎小姐姐

**Comment by hoosin** [comment]
@836104726 哪个小姐姐

**Comment by Hosing2015** [comment]
加油！

**Comment by lihongfei51** [comment]
@836104726 我也以为是知乎的那个小姐姐

**Comment by little-hao** [comment]
知乎来的加一，不过祝你健身成功
