### ISSUE TITLE
吐槽一下，很久木有更新了噢？

### ISSUE THREAD

**Issue by Mr-lidajun** [hoosin/EveryDaySport#11]
还停留在2015年的1月？说好的一起锻炼呢....

**Comment by hoosin** [comment]
多谢吐槽我

**Comment by xfsas** [comment]
多多吐槽，就算是有人一起约好时间的运动，也是不一定坚持的下来。

**Comment by Qianbixin** [comment]
wo

**Comment by ma3252788** [comment]
好吧，刚想锻炼来着

**Comment by iBaiYang** [comment]
这一年还完房贷了？

**Comment by wenglanmin** [comment]
大胆推测楼主35岁生日过了

**Comment by NoviceXue** [comment]
健身这件事！毅力呢？

**Comment by lwwen124** [comment]
@541221507 头像可爱

**Comment by ma3252788** [comment]
同意

2016-12-08 

马春杰 



发件人：wendylwwen <notifications@github.com>
发送时间：2016-12-08 09:57
主题：Re: [hoosin/EveryDaySport] 吐槽一下，很久木有更新了噢？ (#11)
收件人："hoosin/EveryDaySport"<EveryDaySport@noreply.github.com>
抄送："arvin"<tianbing010@126.com>,"Comment"<comment@noreply.github.com>

@541221507 头像可爱

**Comment by yeahjude** [comment]
咦？我好像来晚了。。。

**Comment by iBaiYang** [comment]
哈哈
